# Generated by Django 5.1.1 on 2025-04-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
