# Generated by Django 5.1.1 on 2025-04-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='jobs.skill'),
        ),
    ]
