# Generated by Django 5.1.1 on 2025-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_skill_alter_jobposting_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('offer_made', 'Offer Made')], default='pending', max_length=50),
        ),
    ]
