# Generated by Django 5.1.1 on 2025-04-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationhr',
            name='role',
            field=models.CharField(choices=[('RECRUITER', 'Recruiter'), ('MANAGER', 'HR Manager')], default='RECRUITER', max_length=20),
        ),
    ]
