# Generated by Django 5.1.1 on 2025-04-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationhr',
            name='role',
            field=models.CharField(choices=[('RECRUITER', 'Recruiter')], default='RECRUITER', max_length=20),
        ),
    ]
