# Generated by Django 5.1.1 on 2025-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationhr_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationhr',
            name='role',
            field=models.CharField(choices=[('RECRUITER', 'Recruiter')], default='RECRUITER', max_length=20),
        ),
    ]
