# Generated by Django 5.1.1 on 2025-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, '0/10'), (1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], null=True),
        ),
    ]
